[conections.snowflake]
account = "TSOEQSN-OJ08090"
user = "RAYYAANS"
password = "Snowflake.2025"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "FITNESS"
schema = "PUBLIC"
client_session_keep_alive= true
secrets.toml
